IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Time]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Time] (
    [TimeID]      INT           IDENTITY (1, 1) NOT NULL,
    [Item]        VARCHAR (50)  NOT NULL,
    [TicketNo]    INT           NOT NULL,
    [Start]       VARCHAR (50)  NOT NULL,
    [End]         VARCHAR (50)  NOT NULL,
    [Total]       VARCHAR (50)  NOT NULL,
    [TimeType]    VARCHAR (50)  NOT NULL,
    [Description] VARCHAR (255) NOT NULL,
    [TicketType]  VARCHAR (50)  NOT NULL,
    [Date]        VARCHAR (50)  NOT NULL,
    [IsCaptured]  INT           NULL,
    [SystemUserID]INT           NULL,
    CONSTRAINT CK_Time_TimeID CHECK (TimeID IS NOT NULL AND TimeID > 0),
PRIMARY KEY CLUSTERED ([TimeID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY] 
) ON [PRIMARY]
END

IF COL_LENGTH('Time', 'TimeID') IS NULL
BEGIN
	ALTER TABLE Time ADD TimeID INT IDENTITY (1, 1) NOT NULL
END


IF COL_LENGTH('Time', 'Item') IS NULL
BEGIN
	ALTER TABLE Time ADD Item VARCHAR(50) NOT NULL
END


IF COL_LENGTH('Time', 'TicketNo') IS NULL
BEGIN
	ALTER TABLE Time ADD TicketNo INT NOT NULL
END


IF COL_LENGTH('Time', 'Start') IS NULL
BEGIN
	ALTER TABLE Time ADD Start VARCHAR(50) NOT NULL
END


IF COL_LENGTH('Time', 'End') IS NULL
BEGIN
	ALTER TABLE Time ADD [End] VARCHAR(50) NOT NULL
END


IF COL_LENGTH('Time', 'Total') IS NULL
BEGIN
	ALTER TABLE Time ADD Total VARCHAR(50) NOT NULL
END


IF COL_LENGTH('Time', 'TimeType') IS NULL
BEGIN
	ALTER TABLE Time ADD TimeType VARCHAR(50) NOT NULL
END


IF COL_LENGTH('Time', 'Description') IS NULL
BEGIN
	ALTER TABLE Time ADD Description VARCHAR(255) NOT NULL
END


IF COL_LENGTH('Time', 'TicketType') IS NULL
BEGIN
	ALTER TABLE Time ADD TicketType VARCHAR(50) NOT NULL
END


IF COL_LENGTH('Time', 'Date') IS NULL
BEGIN
	ALTER TABLE Time ADD Date VARCHAR(50) NOT NULL
END


IF COL_LENGTH('Time', 'IsCaptured') IS NULL
BEGIN
	ALTER TABLE Time ADD IsCaptured INT NULL
END


IF COL_LENGTH('Time', 'SystemUserID') IS NULL
BEGIN
	ALTER TABLE Time ADD SystemUserID INT NULL
END

