IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Notes]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Notes] (
    [NoteID]   INT           NOT NULL,
    [Name]     VARCHAR (255) NOT NULL,
    [Note]     VARCHAR (255) NOT NULL,
    [Date]     VARCHAR (255) NOT NULL,
    [ParentID] INT           NOT NULL,
PRIMARY KEY CLUSTERED
(
	[NoteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END

IF COL_LENGTH('Notes', 'NoteID') IS NULL
BEGIN
	ALTER TABLE Notes ADD NoteID INT NULL
END


IF COL_LENGTH('Notes', 'Name') IS NULL
BEGIN
	ALTER TABLE Notes ADD Name VARCHAR(255) NOT NULL
END


IF COL_LENGTH('Notes', 'Note') IS NULL
BEGIN
	ALTER TABLE Notes ADD Note VARCHAR(255) NOT NULL
END


IF COL_LENGTH('Notes', 'Date') IS NULL
BEGIN
	ALTER TABLE Notes ADD Date VARCHAR(255) NOT NULL
END


IF COL_LENGTH('Notes', 'ParentID') IS NULL
BEGIN
	ALTER TABLE Notes ADD ParentID INT NOT NULL
END
