IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Tasks]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Tasks] (
    [TaskID] INT          NOT NULL,
    [Task]   VARCHAR (50) NOT NULL,
    [Status] INT          NOT NULL,
    PRIMARY KEY CLUSTERED
(
	[TaskID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END

IF COL_LENGTH('Tasks', 'TaskID') IS NULL
BEGIN
	ALTER TABLE Tasks ADD TaskID INT NOT NULL
END


IF COL_LENGTH('Tasks', 'Task') IS NULL
BEGIN
	ALTER TABLE Tasks ADD Task VARCHAR(50) NOT NULL
END


IF COL_LENGTH('Tasks', 'Status') IS NULL
BEGIN
	ALTER TABLE Tasks ADD Status INT NOT NULL
END
