IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Config_HS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[Config_HS] (
    [ConfigHSID]	INT					NOT NULL,
    [Key]			VARCHAR (50)		NOT NULL,
	[OldValue]		VARCHAR (255)		NULL,
    [NewValue]		VARCHAR (255)		NOT NULL,
	[Mode]			VARCHAR (1)			NOT NULL,
	[UserID]		INT					NOT NULL,
    PRIMARY KEY CLUSTERED
(
	[ConfigHSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END


IF COL_LENGTH('Config_HS', 'ConfigHSID') IS NULL
BEGIN
	ALTER TABLE Config_HS ADD ConfigHSID INT NOT NULL
END

IF COL_LENGTH('Config_HS', 'Key') IS NULL
BEGIN
	ALTER TABLE Config_HS ADD [Key] VARCHAR(50) NOT NULL
END


IF COL_LENGTH('Config_HS', 'OldValue') IS NULL
BEGIN
	ALTER TABLE Config_HS ADD OldValue VARCHAR(255) NOT NULL
END


IF COL_LENGTH('Config_HS', 'NewValue') IS NULL
BEGIN
	ALTER TABLE Config_HS ADD NewValue VARCHAR(255) NOT NULL
END

IF COL_LENGTH('Config_HS', 'Mode') IS NULL
BEGIN
	ALTER TABLE Config_HS ADD Mode varchar(1) NOT NULL
END

IF COL_LENGTH('Config_HS', 'UserID') IS NULL
BEGIN
	ALTER TABLE Config_HS ADD UserID int NOT NULL
END
