IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TimeTypes]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TimeTypes] (
    [ID]   INT          NOT NULL,
    [Name] VARCHAR (50) NOT NULL,
PRIMARY KEY CLUSTERED ([ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY] 
) ON [PRIMARY]
END

IF COL_LENGTH('TimeTypes', 'ID') IS NULL
BEGIN
	ALTER TABLE TimeTypes ADD ID INT NOT NULL
END


IF COL_LENGTH('TimeTypes', 'Name') IS NULL
BEGIN
	ALTER TABLE TimeTypes ADD Name VARCHAR(50) NOT NULL
END
